2018-03-24 20:59:48,733 [ERROR   ] at test.py <module>.13 - - å•Š
NoneType: None
